import Head from 'next/head'
import { container, main, title, footer } from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={main}>
        <h1 className={title}>
          Vixen and Vine
        </h1>
      </main>

      <footer className={footer}>

      </footer>
    </div>
  )
}
